apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cbx-mcp-server-k8s.fullname" . }}-config
  labels:
    {{- include "cbx-mcp-server-k8s.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | indent 4 }}
